// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var templates = /* array */[
  {
    number: 1,
    model: "amar",
    present: /* array */[
      "o",
      "as",
      "a",
      "amos",
      "áis",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 2,
    model: "temer",
    present: /* array */[
      "o",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 3,
    model: "partir",
    present: /* array */[
      "o",
      "es",
      "e",
      "imos",
      "ís",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 4,
    model: "anunciar",
    present: /* array */[
      "o",
      "as",
      "a",
      "amos",
      "áis",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 5,
    model: "env/i/ar",
    present: /* array */[
      "í/o",
      "í/as",
      "í/a",
      "amos",
      "áis",
      "env/í/an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 6,
    model: "averig/u/ar",
    present: /* array */[
      "o",
      "as",
      "a",
      "amos",
      "áis",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "ü/é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 7,
    model: "act/u/ar",
    present: /* array */[
      "ú/o",
      "ú/as",
      "ú/a",
      "amos",
      "áis",
      "ú/an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 8,
    model: "bailar",
    present: /* array */[
      "o",
      "as",
      "a",
      "amos",
      "áis",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 9,
    model: "a/i/slar",
    present: /* array */[
      "í/o",
      "í/as",
      "í/a",
      "amos",
      "áis",
      "í/an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 10,
    model: "causar",
    present: /* array */[
      "o",
      "as",
      "a",
      "amos",
      "áis",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 11,
    model: "a/u/nar",
    present: /* array */[
      "ú/o",
      "ú/as",
      "ú/a",
      "amos",
      "áis",
      "ú/an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 12,
    model: "peinar",
    present: /* array */[
      "o",
      "as",
      "a",
      "amos",
      "áis",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 13,
    model: "descafe/i/nar",
    present: /* array */[
      "í/o",
      "í/as",
      "í/a",
      "amos",
      "áis",
      "í/an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 14,
    model: "adeudar",
    present: /* array */[
      "o",
      "as",
      "a",
      "amos",
      "áis",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 15,
    model: "reh/u/sar",
    present: /* array */[
      "ú/o",
      "ú/as",
      "ú/a",
      "amos",
      "áis",
      "ú/an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 16,
    model: "ac/e/rtar",
    present: /* array */[
      "ie/o",
      "ie/as",
      "ie/a",
      "amos",
      "áis",
      "ie/an	"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 17,
    model: "adqu/i/rir",
    present: /* array */[
      "ie/o",
      "ie/es",
      "ie/e",
      "imos",
      "ís",
      "ie/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 18,
    model: "agrade/c/er",
    present: /* array */[
      "zc/o",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 19,
    model: "andar",
    present: /* array */[
      "o",
      "as",
      "a",
      "amos",
      "áis",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "uve",
      "uviste",
      "uvo",
      "uvimos",
      "uvisteis",
      "uvieron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 20,
    model: "asir",
    present: /* array */[
      "go",
      "es",
      "e",
      "imos",
      "ís",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 21,
    model: "/cab/er",
    present: /* array */[
      "quep/o",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "cup/e",
      "cup/iste",
      "cup/o",
      "cup/imos",
      "cup/isteis",
      "cup/ieron"
    ],
    future: /* array */[
      "ré",
      "rás",
      "rá",
      "remos",
      "réis",
      "rán"
    ],
    conditional: /* array */[
      "ría",
      "rías",
      "ría",
      "ríamos",
      "ríais",
      "rían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 22,
    model: "caer",
    present: /* array */[
      "igo",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "íste",
      "yó",
      "ímos",
      "ísteis",
      "yeron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "yendo"
  },
  {
    number: 23,
    model: "c/e/ñir",
    present: /* array */[
      "i/o",
      "i/es",
      "i/e",
      "imos",
      "ís",
      "i/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "i/ó",
      "imos",
      "isteis",
      "i/eron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "i/iendo"
  },
  {
    number: 24,
    model: "condu/c/ir",
    present: /* array */[
      "zc/o",
      "es",
      "e",
      "imos",
      "ís",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "j/e",
      "j/iste",
      "j/o",
      "j/imos",
      "j/isteis",
      "j/eron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 25,
    model: "construir",
    present: /* array */[
      "yo",
      "yes",
      "ye",
      "imos",
      "ís",
      "yen"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "yó",
      "imos",
      "isteis",
      "yeron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "yendo"
  },
  {
    number: 26,
    model: "c/o/ntar",
    present: /* array */[
      "ue/o",
      "ue/as",
      "ue/a",
      "amos",
      "áis",
      "ue/an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 27,
    model: "dar",
    present: /* array */[
      "oy",
      "as",
      "a",
      "amos",
      "ais",
      "an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "i",
      "iste",
      "io",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 28,
    model: "d/ec/ir",
    present: /* array */[
      "ig/o",
      "ic/es",
      "ic/e",
      "imos",
      "ís",
      "ic/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "ij/e",
      "ij/iste",
      "ij/o",
      "ij/imos",
      "ij/isteis",
      "ij/eron"
    ],
    future: /* array */[
      "iré",
      "/irás",
      "/irá",
      "/iremos",
      "/iréis",
      "/irán"
    ],
    conditional: /* array */[
      "iría",
      "/irías",
      "/iría",
      "/iríamos",
      "/iríais",
      "/irían"
    ],
    participle: "icho",
    gerund: "iciendo"
  },
  {
    number: 29,
    model: "disc/e/rnir",
    present: /* array */[
      "ie/o",
      "ie/es",
      "ie/e",
      "imos",
      "ís",
      "ie/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 30,
    model: "d/o/rmir",
    present: /* array */[
      "ue/o",
      "ue/es",
      "ue/e",
      "imos",
      "ís",
      "ue/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "u/ió",
      "imos",
      "isteis",
      "u/ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "u/iendo"
  },
  {
    number: 31,
    model: "ent/e/nder",
    present: /* array */[
      "ie/o",
      "ie/es",
      "ie/e",
      "emos",
      "éis",
      "ie/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 32,
    model: "/ergu/ir",
    present: /* array */[
      "yerg/o",
      "yergu/es",
      "yergu/e",
      "imos",
      "ís",
      "yergu/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "irgu/ió",
      "imos",
      "isteis",
      "irgu/ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "irgu/iendo"
  },
  {
    number: 33,
    model: "/e/rrar",
    present: /* array */[
      "ye/o",
      "ye/as",
      "ye/a",
      "amos",
      "áis",
      "ye/an"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "é",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 34,
    model: "estar",
    present: /* array */[
      "oy",
      "ás",
      "á",
      "amos",
      "áis",
      "án"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "uve",
      "uviste",
      "uvo",
      "uvimos",
      "uvisteis",
      "uvieron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 35,
    model: "h/ab/er",
    present: /* array */[
      "e",
      "/as",
      "/a",
      "/emos",
      "éis",
      "/an"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "ub/e",
      "ub/iste",
      "ub/o",
      "ub/imos",
      "ub/isteis",
      "ub/ieron"
    ],
    future: /* array */[
      "ré",
      "rás",
      "rá",
      "remos",
      "réis",
      "rán"
    ],
    conditional: /* array */[
      "ría",
      "rías",
      "ría",
      "ríamos",
      "ríais",
      "rían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 36,
    model: "/hac/er",
    present: /* array */[
      "hag/o",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "hic/e",
      "hic/iste",
      "hiz/o",
      "hic/imos",
      "hic/isteis",
      "hic/ieron"
    ],
    future: /* array */[
      "har/é",
      "har/ás",
      "har/á",
      "har/emos",
      "har/éis",
      "har/án"
    ],
    conditional: /* array */[
      "har/ía",
      "har/ías",
      "har/ía",
      "har/íamos",
      "har/íais",
      "har/ían"
    ],
    participle: "hecho/",
    gerund: "iendo"
  },
  {
    number: 37,
    model: "ir",
    present: /* array */[
      "voy",
      "vas",
      "va",
      "vamos",
      "vais",
      "van"
    ],
    imperfect: /* array */[
      "iba",
      "ibas",
      "iba",
      "íbamos",
      "ibais",
      "iban"
    ],
    preterite: /* array */[
      "fui",
      "fuiste",
      "fue",
      "fuimos",
      "fuisteis",
      "fueron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "yendo"
  },
  {
    number: 38,
    model: "j/u/gar",
    present: /* array */[
      "ue/go",
      "ue/gas",
      "ue/ga",
      "amos",
      "áis",
      "ue/gan"
    ],
    imperfect: /* array */[
      "aba",
      "abas",
      "aba",
      "ábamos",
      "abais",
      "aban"
    ],
    preterite: /* array */[
      "ué",
      "aste",
      "ó",
      "amos",
      "asteis",
      "aron"
    ],
    future: /* array */[
      "aré",
      "arás",
      "ará",
      "aremos",
      "aréis",
      "arán"
    ],
    conditional: /* array */[
      "aría",
      "arías",
      "aría",
      "aríamos",
      "aríais",
      "arían"
    ],
    participle: "ado",
    gerund: "ando"
  },
  {
    number: 39,
    model: "leer",
    present: /* array */[
      "o",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "íste",
      "yó",
      "ímos",
      "ísteis",
      "yeron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "yendo"
  },
  {
    number: 40,
    model: "lu/c/ir",
    present: /* array */[
      "zc/o",
      "es",
      "e",
      "imos",
      "ís",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 41,
    model: "m/o/ver",
    present: /* array */[
      "ue/o",
      "ue/es",
      "ue/e",
      "emos",
      "éis",
      "ue/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 42,
    model: "mullir",
    present: /* array */[
      "o",
      "es",
      "e",
      "imos",
      "ís",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ó",
      "imos",
      "isteis",
      "eron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "endo"
  },
  {
    number: 43,
    model: "oir",
    present: /* array */[
      "igo",
      "yes",
      "ye",
      "ímos",
      "ís",
      "yen"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "íste",
      "yó",
      "ímos",
      "ísteis",
      "yeron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "yendo"
  },
  {
    number: 44,
    model: "/o/ler",
    present: /* array */[
      "hue/o",
      "hue/es",
      "hue/e",
      "emos",
      "éis",
      "hue/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 45,
    model: "p/e/dir",
    present: /* array */[
      "i/o",
      "i/es",
      "i/e",
      "imos",
      "ís",
      "i/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "i/ió",
      "imos",
      "isteis",
      "i/ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "i/iendo"
  },
  {
    number: 46,
    model: "p/o/der",
    present: /* array */[
      "ue/o",
      "ue/es",
      "ue/e",
      "emos",
      "éis",
      "ue/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "u/e",
      "u/iste",
      "u/o",
      "u/imos",
      "u/isteis",
      "u/ieron"
    ],
    future: /* array */[
      "ré",
      "rás",
      "rá",
      "remos",
      "réis",
      "rán"
    ],
    conditional: /* array */[
      "ría",
      "rías",
      "ría",
      "ríamos",
      "ríais",
      "rían"
    ],
    participle: "ido",
    gerund: "u/iendo"
  },
  {
    number: 47,
    model: "p/on/er",
    present: /* array */[
      "go",
      "es (és)",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "u/se",
      "u/siste",
      "u/so",
      "u/simos",
      "u/sisteis",
      "u/sieron"
    ],
    future: /* array */[
      "dré",
      "drás",
      "drá",
      "dremos",
      "dréis",
      "drán"
    ],
    conditional: /* array */[
      "dría",
      "drías",
      "dría",
      "dríamos",
      "dríais",
      "drían"
    ],
    participle: "u/esto",
    gerund: "iendo"
  },
  {
    number: 48,
    model: "p/u/drir",
    present: /* array */[
      "o",
      "es",
      "e",
      "imos",
      "podrimos",
      "ís",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "podríamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron",
      "podrieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "podriremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "podriríamos",
      "iríais",
      "irían"
    ],
    participle: "o/ido",
    gerund: "iendo"
  },
  {
    number: 49,
    model: "qu/er/er",
    present: /* array */[
      "ier/o",
      "ier/es",
      "ier/e",
      "emos",
      "éis",
      "ier/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "is/e",
      "is/iste",
      "is/o",
      "is/imos",
      "is/isteis",
      "is/ieron"
    ],
    future: /* array */[
      "ré",
      "rás",
      "rá",
      "remos",
      "réis",
      "rán"
    ],
    conditional: /* array */[
      "ría",
      "rías",
      "ría",
      "ríamos",
      "ríais",
      "rían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 50,
    model: "roer",
    present: /* array */[
      "igo",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "íste",
      "yó",
      "ímos",
      "ísteis",
      "yen"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "yendo"
  },
  {
    number: 51,
    model: "s/ab/er",
    present: /* array */[
      "é",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "up/e",
      "up/iste",
      "up/o",
      "up/imos",
      "up/isteis",
      "up/ieron"
    ],
    future: /* array */[
      "ré",
      "rás",
      "rá",
      "remos",
      "réis",
      "rán"
    ],
    conditional: /* array */[
      "ría",
      "rías",
      "ría",
      "ríamos",
      "ríais",
      "rían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 52,
    model: "salir",
    present: /* array */[
      "go",
      "es",
      "e",
      "imos",
      "ís",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "dré",
      "drás",
      "drá",
      "dremos",
      "dréis",
      "drán"
    ],
    conditional: /* array */[
      "dría",
      "drías",
      "dría",
      "dríamos",
      "dríais",
      "drían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 53,
    model: "s/e/ntir",
    present: /* array */[
      "ie/o",
      "ie/es",
      "ie/e",
      "imos",
      "ís",
      "ie/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "sintió",
      "imos",
      "isteis",
      "sinie/ron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ido",
    gerund: "i/iendo"
  },
  {
    number: 54,
    model: "/s/er",
    present: /* array */[
      "/soy",
      "/eres",
      "/es",
      "/somos",
      "/sois",
      "/son"
    ],
    imperfect: /* array */[
      "/era",
      "/eras",
      "/era",
      "/éramos",
      "/erais",
      "/eran"
    ],
    preterite: /* array */[
      "/fui",
      "/fuiste",
      "/fue",
      "/fuimos",
      "/fuisteis",
      "/fueron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 55,
    model: "sonr/e/ir",
    present: /* array */[
      "/ío",
      "/íes",
      "/íe",
      "ímos",
      "ís",
      "/íen"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "íste",
      "/ió",
      "ímos",
      "ísteis",
      "/ieron"
    ],
    future: /* array */[
      "iré",
      "irás",
      "irá",
      "iremos",
      "iréis",
      "irán"
    ],
    conditional: /* array */[
      "iría",
      "irías",
      "iría",
      "iríamos",
      "iríais",
      "irían"
    ],
    participle: "ído",
    gerund: "iendo"
  },
  {
    number: 56,
    model: "tañer",
    present: /* array */[
      "o",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ó",
      "imos",
      "isteis",
      "eron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "endo"
  },
  {
    number: 57,
    model: "t/en/er",
    present: /* array */[
      "go",
      "ien/es",
      "ien/e",
      "emos",
      "éis",
      "ien/en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "uv/e",
      "uv/iste",
      "uv/o",
      "uv/imos",
      "uv/isteis",
      "uv/ieron"
    ],
    future: /* array */[
      "dré",
      "drás",
      "drá",
      "dremos",
      "dréis",
      "drán"
    ],
    conditional: /* array */[
      "dría",
      "drías",
      "dría",
      "dríamos",
      "dríais",
      "drían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 58,
    model: "traer",
    present: /* array */[
      "igo",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "je",
      "jiste",
      "jo",
      "jimos",
      "jisteis",
      "jeron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "yendo"
  },
  {
    number: 59,
    model: "valer",
    present: /* array */[
      "go",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "dré",
      "drás",
      "drá",
      "dremos",
      "dréis",
      "drán"
    ],
    conditional: /* array */[
      "dría",
      "drías",
      "dría",
      "dríamos",
      "dríais",
      "drían"
    ],
    participle: "ido",
    gerund: "iendo"
  },
  {
    number: 60,
    model: "v/e/nir",
    present: /* array */[
      "go",
      "ie/ne",
      "ie/ne",
      "imos",
      "ís",
      "ie/nen"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "i/e",
      "i/iste",
      "i/o",
      "i/imos",
      "i/isteis",
      "i/ieron"
    ],
    future: /* array */[
      "dré",
      "drás",
      "drá",
      "dremos",
      "dréis",
      "drán"
    ],
    conditional: /* array */[
      "dría",
      "drías",
      "dría",
      "dríamos",
      "dríais",
      "drían"
    ],
    participle: "ido",
    gerund: "i/iendo"
  },
  {
    number: 61,
    model: "ver",
    present: /* array */[
      "eo",
      "es",
      "e",
      "emos",
      "eis",
      "en"
    ],
    imperfect: /* array */[
      "eía",
      "eías",
      "eía",
      "eíamos",
      "eíais",
      "eían"
    ],
    preterite: /* array */[
      "i",
      "iste",
      "io",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "isto",
    gerund: "iendo"
  },
  {
    number: 62,
    model: "ya/c/er",
    present: /* array */[
      "zc/",
      "es",
      "e",
      "emos",
      "éis",
      "en"
    ],
    imperfect: /* array */[
      "ía",
      "ías",
      "ía",
      "íamos",
      "íais",
      "ían"
    ],
    preterite: /* array */[
      "í",
      "iste",
      "ió",
      "imos",
      "isteis",
      "ieron"
    ],
    future: /* array */[
      "eré",
      "erás",
      "erá",
      "eremos",
      "eréis",
      "erán"
    ],
    conditional: /* array */[
      "ería",
      "erías",
      "ería",
      "eríamos",
      "eríais",
      "erían"
    ],
    participle: "ido",
    gerund: "iendo"
  }
];

exports.templates = templates;
/* No side effect */
