// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Patterns$Spanishverb = require("./Patterns.bs.js");

var verbList = /* array */[
  {
    spanish: "hablar",
    english: "to speak",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "estudiar",
    english: "to study",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "escuchar",
    english: "to listen to",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "visitar",
    english: "to visit",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "viajar",
    english: "to travel",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "enseñar",
    english: "to teach",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "llegar",
    english: "to arrive",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "llevar",
    english: "to take, carry, wear",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "bailar",
    english: "to dance",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "lavar",
    english: "to wash",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "lavar",
    english: "to wash one’s self",
    conj: /* AR */0,
    type_: /* Regular */0,
    reflexive: true,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  },
  {
    spanish: "leer",
    english: "to read",
    conj: /* ER */1,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 38)
  },
  {
    spanish: "comer",
    english: "to eat",
    conj: /* ER */1,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 1)
  },
  {
    spanish: "beber",
    english: "to drink",
    conj: /* ER */1,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 1)
  },
  {
    spanish: "ent/e/nder",
    english: "to understand",
    conj: /* ER */1,
    type_: /* StemChanging */1,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 30)
  },
  {
    spanish: "vivir",
    english: "to live",
    conj: /* IR */2,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 2)
  },
  {
    spanish: "d/o/rmir",
    english: "to sleep",
    conj: /* IR */2,
    type_: /* StemChanging */1,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 29)
  },
  {
    spanish: "d/o/rmir",
    english: "to go to sleep / fall asleep",
    conj: /* IR */2,
    type_: /* StemChanging */1,
    reflexive: true,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 29)
  },
  {
    spanish: "decidir",
    english: "to decide",
    conj: /* IR */2,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 2)
  },
  {
    spanish: "escribir",
    english: "to write",
    conj: /* IR */2,
    type_: /* Regular */0,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 2)
  },
  {
    spanish: "estar",
    english: "to be",
    conj: /* AR */0,
    type_: /* Irregular */2,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 33)
  },
  {
    spanish: "/s/er",
    english: "to be",
    conj: /* ER */1,
    type_: /* Irregular */2,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 53)
  },
  {
    spanish: "ir",
    english: "to go",
    conj: /* IR */2,
    type_: /* Irregular */2,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 36)
  },
  {
    spanish: "t/en/er",
    english: "to have",
    conj: /* ER */1,
    type_: /* Irregular */2,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 56)
  },
  {
    spanish: "p/o/der",
    english: "to be able [to]",
    conj: /* ER */1,
    type_: /* Irregular */2,
    reflexive: false,
    pattern: Caml_array.caml_array_get(Patterns$Spanishverb.templates, 45)
  }
];

exports.verbList = verbList;
/* No side effect */
