// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Patterns$Spanishverb = require("./Patterns.bs.js");

var verbList = /* array */[
  /* record */[
    /* spanish */"hablar",
    /* english */"to speak",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"gustar",
    /* english */"to like",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */true,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"estudiar",
    /* english */"to study",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"escuchar",
    /* english */"to listen to",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"visitar",
    /* english */"to visit",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"viajar",
    /* english */"to travel",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"enseñar",
    /* english */"to teach",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"llegar",
    /* english */"to arrive",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"llevar",
    /* english */"to take, carry, wear",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"bailar",
    /* english */"to dance",
    /* conj : AR */0,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 0)
  ],
  /* record */[
    /* spanish */"leer",
    /* english */"to read",
    /* conj : ER */1,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 38)
  ],
  /* record */[
    /* spanish */"comer",
    /* english */"to eat",
    /* conj : ER */1,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 1)
  ],
  /* record */[
    /* spanish */"beber",
    /* english */"to drink",
    /* conj : ER */1,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 1)
  ],
  /* record */[
    /* spanish */"ent/e/nder",
    /* english */"to understand",
    /* conj : ER */1,
    /* type_ : StemChanging */1,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 30)
  ],
  /* record */[
    /* spanish */"vivir",
    /* english */"to live",
    /* conj : IR */2,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 2)
  ],
  /* record */[
    /* spanish */"d/o/rmir",
    /* english */"to sleep",
    /* conj : IR */2,
    /* type_ : StemChanging */1,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 29)
  ],
  /* record */[
    /* spanish */"decidir",
    /* english */"to decide",
    /* conj : IR */2,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 2)
  ],
  /* record */[
    /* spanish */"escribir",
    /* english */"to write",
    /* conj : IR */2,
    /* type_ : Regular */0,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 2)
  ],
  /* record */[
    /* spanish */"estar",
    /* english */"to be",
    /* conj : AR */0,
    /* type_ : Irregular */2,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 33)
  ],
  /* record */[
    /* spanish */"/s/er",
    /* english */"to be",
    /* conj : ER */1,
    /* type_ : Irregular */2,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 53)
  ],
  /* record */[
    /* spanish */"ir",
    /* english */"to go",
    /* conj : IR */2,
    /* type_ : Irregular */2,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 36)
  ],
  /* record */[
    /* spanish */"t/en/er",
    /* english */"to have",
    /* conj : ER */1,
    /* type_ : Irregular */2,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 56)
  ],
  /* record */[
    /* spanish */"p/o/der",
    /* english */"to be able (to)",
    /* conj : ER */1,
    /* type_ : Irregular */2,
    /* reflexive */false,
    /* pattern */Caml_array.caml_array_get(Patterns$Spanishverb.templates, 45)
  ]
];

exports.verbList = verbList;
/* No side effect */
